export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const ARTICLES_FETCH_SUCCEEDED = "ARTICLES_FETCH_SUCCEEDED";
export const ARTICLES_FETCH_ERROR = "ARTICLES_FETCH_ERROR";